# Site
title: Victor Tang
subtitle:
description:
author: Victor Tang
bio: "Engineer @ Akamai - I also build web-based tools, games and interesting experiences."
language:
timezone:

google_analytics:
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.vtange.net
avatar: https://en.gravatar.com/userimage/81829932/8691582a2e6a7799db4c14a969fbe603.png?size=200
logo: fonts/logo.png
favicon: fonts/favicon.png
root: /
permalink: :title/ ##:year/:month/:day/ old
permalink_defaults:
featured:
  - title: See my works
    desc: "A gallery of the various apps and design work I've done at various stages in my career"
    multi_url:
      - "http://res.cloudinary.com/dmj8qtant/image/upload/c_thumb,g_face,h_275,w_400/v1452900630/gxx0rmutpczk8fv0vodq.jpg"
      - "http://res.cloudinary.com/dmj8qtant/image/upload/c_thumb,g_face,h_275,w_400/v1452900630/gwl76sq07wze0cuuykdz.jpg"
      - "http://res.cloudinary.com/dmj8qtant/image/upload/c_thumb,g_face,h_275,w_400/v1452900630/qbgim9p9ervkkxqrqjej.jpg"
      - "http://res.cloudinary.com/dmj8qtant/image/upload/c_thumb,g_face,h_275,w_400/v1452900630/ri3qe7vg5ldbcu4l1rnq.jpg"
      - "http://res.cloudinary.com/dmj8qtant/image/upload/c_thumb,g_face,h_275,w_400/v1452900630/egjehu0yamywhk8ke0wa.jpg"
      - "http://res.cloudinary.com/dmj8qtant/image/upload/c_thumb,g_face,h_275,w_400/v1452900630/mlpbzhisax8kdtrsaxuu.jpg"
      - "http://res.cloudinary.com/dmj8qtant/image/upload/c_thumb,g_face,h_275,w_400/v1452900630/ftxrst42nebekzhunr2d.jpg"
      - "http://res.cloudinary.com/dmj8qtant/image/upload/c_thumb,g_face,h_275,w_400/v1452900630/hi12fjlvazyjmnqnrfjp.jpg"
      - "http://res.cloudinary.com/dmj8qtant/image/upload/c_thumb,g_face,h_275,w_400/v1452900630/lbweuszj5mblgdhma1aj.jpg"
      - "http://res.cloudinary.com/dmj8qtant/image/upload/c_thumb,g_face,h_275,w_400/v1452900630/lainicav200larnipqgk.jpg"
      - "http://res.cloudinary.com/dmj8qtant/image/upload/c_thumb,g_face,h_275,w_400/v1452900630/hrmewamnwo9vij01w212.jpg"
      - "http://res.cloudinary.com/dmj8qtant/image/upload/c_thumb,g_face,h_275,w_400/v1452900630/qxlepewnyqaopzt0osgl.jpg"
    mini_url:
    bg_url:
    url: works
#  - title: 
#    ctr_x: 50
#    ctr_y: 70
#    url: 
#  - title: 
#    url: 

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: false
original-md:

## Themes: https://hexo.io/themes/
theme: casper

### EDIT MODE
markdown_edit: false

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:
